getwd()
ad_org_train=read.csv("C:/rWork/rProjects/R-in-Action/analytics/vidooly_analytics/vidooly_ad.csv",stringsAsFactors = FALSE)
ad_org_test=read.csv("C:/rWork/rProjects/R-in-Action/analytics/vidooly_analytics/ad_test_data.csv",stringsAsFactors = FALSE)
str(ad_org_test)
colSums(is.na(ad_org_test))
as.data.frame(colSums(is.na(ad_org_train)))
as.data.frame(colSums(is.na(ad_org_test)))
summary(ad_org_train)
library(zoo)
library(dplyr)
ad_org_train %>%
  select(vidid,views,likes,dislikes,comment) %>%
  filter(comment == 870)
library(devtools)
install_github(repo = "modify", username = "skranz")
library(microbenchmark)
library(modify)
modify(ad_org_train, comment == 2008, comment = 870)
str(ad_org_train)
View(ad_org_train)
ad_org_train$views = as.integer(ad_org_train$views)
ad_org_train$likes = as.integer(ad_org_train$likes)
ad_org_train$dislikes = as.integer(ad_org_train$dislikes)
ad_org_train$comment = as.integer(ad_org_train$comment)
ad_org_test$views = as.integer(ad_org_test$views)
ad_org_test$likes = as.integer(ad_org_test$likes)
ad_org_test$dislikes = as.integer(ad_org_test$dislikes)
ad_org_test$comment = as.integer(ad_org_test$comment)
median(ad_org_train$views,na.rm = T)
median(ad_org_train$likes,na.rm = T)
median(ad_org_train$dislikes,na.rm = T)
median(ad_org_train$comment,na.rm = T)
Vidid = ad_org_train$vidid
ad_org_train$vidid = NULL
ad_org_train$published = NULL
ad_org_train$duration = NULL
ad_org_test$published = NULL
ad_org_test$duration = NULL
ad_org_test %>%
  select(vidid,views,likes,dislikes,comment) %>%
  filter(comment == 669)
modify(ad_org_test, vidid == "VID_14106", comment = 275)
median(ad_org_test$views,na.rm = T)
median(ad_org_test$likes, na.rm = T)
median(ad_org_test$dislikes, na.rm = T)
median(ad_org_test$comment, na.rm = T)
View(ad_org_test)
ad_org_train$views = as.factor(ad_org_train$views)
ad_org_train$likes = as.factor(ad_org_train$likes)
ad_org_train$dislikes = as.factor(ad_org_train$dislikes)
ad_org_train$comment = as.factor(ad_org_train$comment)
library(randomForest)
Model1 = randomForest(adview ~ views + likes + dislikes + comment + category, data = ad_org_train, nodesize = 5)
summary(Model1)
plot((Model1))
pred = predict(Model1, newdata = ad_org_test, type = "class")
pred = as.integer(pred)
Solution = data.frame(vid_id = ad_org_test$vidid, ad_view = pred, check.rows = F)
write.csv(Solution, file = "Ad_view_pred.csv", row.names = F)
